# Aula 1

## Vídeo 1.2 - Carregando textos

In [1]:
import pandas as pd

In [2]:
url ='https://github.com/allanspadini/curso-tensorflow-proxima-palavra/raw/main/dados/train.zip'

In [3]:
df = pd.read_csv(url, header=None, names=['ClassIndex','Título','Descrição'])
df.head()

ClassIndex                                             Título  \
0           3  Wall St. Bears Claw Back Into the Black (Reuters)   
1           3  Carlyle Looks Toward Commercial Aerospace (Reu...   
2           3    Oil and Economy Cloud Stocks' Outlook (Reuters)   
3           3  Iraq Halts Oil Exports from Main Southern Pipe...   
4           3  Oil prices soar to all-time record, posing new...   

                                           Descrição  
0  Reuters - Short-sellers, Wall Street's dwindli...  
1  Reuters - Private investment firm Carlyle Grou...  
2  Reuters - Soaring crude prices plus worries\ab...  
3  Reuters - Authorities have halted oil export\f...  
4  AFP - Tearaway world oil prices, toppling reco...

https://github.com/allanspadini/curso-tensorflow-proxima-palavra/blob/main/dados/classes.txt

In [4]:
df['Texto'] = df['Título'] + ' ' + df['Descrição']

In [5]:
df['Texto']

0         Wall St. Bears Claw Back Into the Black (Reute...
1         Carlyle Looks Toward Commercial Aerospace (Reu...
2         Oil and Economy Cloud Stocks' Outlook (Reuters...
3         Iraq Halts Oil Exports from Main Southern Pipe...
4         Oil prices soar to all-time record, posing new...
                                ...                        
119995    Pakistan's Musharraf Says Won't Quit as Army C...
119996    Renteria signing a top-shelf deal Red Sox gene...
119997    Saban not going to Dolphins yet The Miami Dolp...
119998    Today's NFL games PITTSBURGH at NY GIANTS Time...
119999    Nets get Carter from Raptors INDIANAPOLIS -- A...
Name: Texto, Length: 120000, dtype: object

In [6]:
df['ClassIndex'] = df['ClassIndex'] - 1

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_treino, X_teste, y_treino,y_teste = train_test_split(df['Texto'].values, df['ClassIndex'].values, test_size=0.2, random_state=4266)

## Vídeo 1.3 - Codificando o texto

In [9]:
import tensorflow as tf

2024-06-19 16:50:01.352268: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-19 16:50:02.066188: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [10]:
VOCAB_SIZE = 1000
encoder = tf.keras.layers.TextVectorization(
    max_tokens=VOCAB_SIZE)


2024-06-19 16:50:02.717628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 20974 MB memory:  -> device: 0, name: NVIDIA L4, pci bus id: 0000:35:00.0, compute capability: 8.9


In [11]:
encoder.adapt(X_treino)

In [12]:
encoder.get_vocabulary()[::10]

['',
 '39s',
 'it',
 'was',
 'more',
 'company',
 'than',
 'microsoft',
 'prices',
 'people',
 'next',
 'sales',
 'state',
 'most',
 'profit',
 'lead',
 'online',
 '39t',
 'red',
 'during',
 'say',
 'between',
 'country',
 'mobile',
 'quarter',
 'being',
 'dollar',
 'stock',
 'sox',
 'olympic',
 'users',
 'price',
 'how',
 'peace',
 'six',
 'key',
 'i',
 'should',
 'financial',
 'leaders',
 'house',
 'sun',
 'used',
 'seven',
 'israel',
 'future',
 'trial',
 'half',
 'customers',
 'defense',
 'arafat',
 'northern',
 'due',
 'men',
 'hopes',
 'using',
 'scored',
 'university',
 'texas',
 'mark',
 'we',
 'accused',
 'profits',
 '18',
 'possible',
 'call',
 'rally',
 'teams',
 'division',
 '7',
 'takeover',
 'production',
 'outlook',
 'began',
 'helped',
 'opening',
 'sept',
 'spain',
 'hours',
 'starting',
 'nine',
 'pressure',
 'executives',
 'personal',
 'once',
 'italian',
 'push',
 'continued',
 'rising',
 'kill',
 'powerful',
 'side',
 'designed',
 'groups',
 'mission',
 'najaf',
 '

In [13]:
Exemplo = "Today's NFL games PITTSBURGH at NY GIANTS"

In [14]:
encoder(Exemplo)

<tf.Tensor: shape=(7,), dtype=int64, numpy=array([  1, 713, 202,   1,  14,   1, 516])>

## Vídeo 1.4 - Criando um modelo

In [15]:
modelo = tf.keras.Sequential([
    encoder,
    tf.keras.layers.Embedding(
        input_dim=len(encoder.get_vocabulary()),
        output_dim=16,
        # Use masking to handle the variable sequence lengths
        mask_zero=True),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(4, activation='softmax')

])

In [16]:
# Compilar o modelo
modelo.compile(optimizer=tf.keras.optimizers.Adam(1e-4), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

https://projector.tensorflow.org/

In [17]:
X_teste[0]

'Border Patrol Training Moves Near Mexico (AP) AP - Incoming Border Patrol agents will train closer to the U.S.-Mexican border when the federal government relocates their academy to Artesia, N.M., Customs and Border Protection announced Thursday.'

In [18]:
y_teste[0]

0

In [19]:
X_teste.shape

(24000,)

In [20]:
modelo.predict(X_teste[:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step


array([[0.24645628, 0.24776942, 0.2520367 , 0.25373763]], dtype=float32)

In [21]:
modelo.predict(X_teste[:1]).argmax(axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


array([3])